from fpdf import FPDF
import os
from datetime import datetime


class MedicalReport(FPDF):
    def header(self):
        # --- Branding Section ---
        self.set_font('Arial', 'B', 16)
        self.set_text_color(0, 74, 153)  # Deep Medical Blue
        self.cell(0, 10, 'Brain tumor detection System | Diagnostic Report', 0, 1, 'L')

        # Sub-header line
        self.set_draw_color(0, 74, 153)
        self.set_line_width(0.5)
        self.line(10, 22, 200, 22)
        self.ln(15)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()} - Generated by Brain tumor Detection System', 0, 0, 'C')


def create_pdf(scan, doctor_name, upload_folder, output_path):
    """
    Generates a professional PDF report with the MRI image.
    """
    pdf = MedicalReport()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # --- 1. Patient & Doctor Details ---
    pdf.set_font("Arial", 'B', 12)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 8, "EXAMINATION DETAILS", 0, 1, 'L')

    pdf.set_font("Arial", size=11)
    # Using a helper to align text nicely
    pdf.cell(50, 8, "Ref Doctor:", 0, 0);
    pdf.cell(0, 8, f"Dr. {doctor_name}", 0, 1)
    pdf.cell(50, 8, "Patient ID:", 0, 0);
    pdf.cell(0, 8, f"{scan.patient_id}", 0, 1)
    pdf.cell(50, 8, "Scan Date:", 0, 0);
    pdf.cell(0, 8, f"{scan.upload_date.strftime('%Y-%m-%d %H:%M')}", 0, 1)
    pdf.cell(50, 8, "Report ID:", 0, 0);
    pdf.cell(0, 8, f"RPT-{scan.id:04d}", 0, 1)
    pdf.ln(10)

    # --- 2. Diagnostic Result (Highlighted) ---
    pdf.set_fill_color(240, 248, 255)  # Light AliceBlue background
    pdf.rect(10, pdf.get_y(), 190, 25, 'F')  # Background rectangle

    pdf.set_xy(15, pdf.get_y() + 5)
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(60, 10, "DIAGNOSIS:", 0, 0)

    # Color Logic: Red for Tumor, Green for No Tumor
    if "No Tumor" in scan.tumor_type:
        pdf.set_text_color(0, 128, 0)  # Green
    else:
        pdf.set_text_color(220, 20, 60)  # Crimson Red

    pdf.cell(0, 10, f"{scan.tumor_type.upper()}", 0, 1)

    pdf.set_x(15)
    pdf.set_font("Arial", '', 12)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(60, 8, "Model Confidence:", 0, 0)
    pdf.cell(0, 8, f"{scan.confidence}%", 0, 1)
    pdf.ln(15)

    # --- 3. MRI Image Embedding ---
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, "SCANNED IMAGERY", 0, 1, 'L')

    # Construct full image path
    image_path = os.path.join(upload_folder, scan.filename)

    if os.path.exists(image_path):
        # (x, y, w) -> Centered image, width 100mm
        pdf.image(image_path, x=55, w=100)
    else:
        pdf.set_text_color(255, 0, 0)
        pdf.cell(0, 10, "[Error: Source Image Not Found]", 0, 1, 'C')

    pdf.ln(15)

    # --- 4. System Interpretation & Disclaimer ---
    pdf.set_font("Arial", 'B', 11)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 8, "INTERPRETATION:", 0, 1)

    pdf.set_font("Arial", '', 10)
    summary_text = (
        f"The AI model (VGG16-based) has analyzed the input MRI scan. "
        f"Based on feature extraction, the system has identified patterns consistent with {scan.tumor_type} "
        f"with a confidence interval of {scan.confidence}%."
    )
    pdf.multi_cell(0, 5, summary_text)
    pdf.ln(10)

    # Legal Disclaimer (Crucial for Medical AI)
    pdf.set_font("Arial", 'I', 9)
    pdf.set_text_color(100, 100, 100)
    disclaimer = (
        "DISCLAIMER: This report is generated by an Artificial Intelligence system and is intended "
        "for screening assistance only. It does not constitute a final medical diagnosis. "
        "All results must be verified by a certified radiologist."
    )
    pdf.multi_cell(0, 5, disclaimer)

    # Output
    pdf.output(output_path)
    return output_path
